title: Dr. Martín Lozano | Research, Teaching, and Resources in Quantitative Finance
subtitle: Research, Teaching, and Resources in Quantitative Finance
site-url: https://mlozanoqf.github.io/
description: Research, teaching, tutorials, and practical tools in quantitative finance by Dr. Martín Lozano.
image: "mlozano muppet.png"
#author: Dr. Martín Lozano.
date-modified: now
date-format: "MMMM D, YYYY, HH:mm:ss a."


# abstract: This material relies on @Hull credit risk chapters and Lore Dirick credit risk DataCamp course. Some mathematical background is skipped to emphasize the data analysis, model logic, discussion, graphical approach and R coding [@Rref]. As in the philosophy of @knuth1984literate, the objective of this document is to explain to human beings what we want a computer to do as literate programming. This is a work in progress and it is under revision.
# bibliography: references.bib

theme: flatly

format:
  html:
    favicon: "mlozano muppet.png"
    open-graph: true
    #toc: true
    toc-title: Contents
    smooth-scroll: true
    code-fold: true
    code-tools:
      source: false
      toggle: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-line-numbers: true
    number-sections: false
    crossref:
      chapters: true
    toc-location: left
    toc-depth: 2
    page-layout: full
    include-after-body: analytics.html
    include-in-header:
      - favicon.html
      - back-to-top.html
      - progressbar.html

link-citations: true
