---
title: Quantitative finance with `r fontawesome::fa("r-project")` <span style="color:white">R</span>
#title: "**\\Huge Quantitative finance with R (QFR). c  \n \\fontsize{100}{100}\\faLaptopCode  \\vspace{20 mm}  \n\\Huge Dr. Martín Lozano.**"

subtitle: Dr. Martín Lozano.
#author:
#   - name: Contact. [Google Sites.](https://sites.google.com/site/mlozanoqf/)
#     affiliation: https://sites.google.com/site/mlozanoqf/
#     email: martin.lozano@udem.edu
#   - name: Jack, the Supposed Contributor
#     affiliation: Living Room Couch
date: Current `r fontawesome::fa("code-branch") ` `r format(Sys.time(), '%d %b %Y, %H:%M:%S.')`
#abstract: As in the philosophy of Donald Knuth, the objective of this document is to explain to human beings what we want a computer to do as literate programming. This is a work in progress and it is under revision.
output:
  html_document:
    #toc: true
    #toc_float: true
    toc_depth: 2
    number_sections: true
    #code_folding: hide
 #   code_download: TRUE
    theme: readable
    includes:
      after_body: analytics.html
header-includes:
- \usepackage{fontawesome}
---


```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
library(fontawesome)
```


```{r, xaringanExtra-clipboard, echo=FALSE}
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa fa-clone fa-2x\" style=\"color: #301e64\"></i>",
    success_text = "<i class=\"fa fa-check fa-2x\" style=\"color: #90BE6D\"></i>",
    error_text = "<i class=\"fa fa-times fa-2x\" style=\"color: #F94144\"></i>"
  ),
  rmarkdown::html_dependency_font_awesome()
)
```

````{=html}
```{r, echo=FALSE, results='asis'}
xfun::file_string('contact.html')
```
````


# Contents: {-}

# [Credit risk](https://mlozanoqf.github.io/tutorial_arf/) [`r fa("credit-card", fill = "black")`](https://mlozanoqf.github.io/tutorial_arf/)

# [Forecasting](https://mlozanoqf.github.io/tutorial_emf/) [`r fa("chart-line", fill = "black")`](https://mlozanoqf.github.io/tutorial_emf/)

# [Options and VaR](https://mlozanoqf.github.io/tutorial_if/) [`r fa("cogs", fill = "black")`](https://mlozanoqf.github.io/tutorial_if/)

# [Financial modeling](https://mlozanoqf.github.io/tutorial_pmf/) [`r fa("laptop-code", fill = "black")`](https://mlozanoqf.github.io/tutorial_pmf/)

